version: "3.8"

services:
  api:
    image: lp-programming-challenge-1:latest
    container_name: animals_api
    ports:
      - "3123:3123"
    healthcheck:
      test: ["CMD", "sh", "-lc", "wget -qO- http://localhost:3123/ | grep -q HELLO || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  loader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: animals_loader
    depends_on:
      api:
        condition: service_healthy
    environment:
      - ANIMALS_BASE_URL=http://api:3123
    command: ["python", "loader.py", "--concurrency", "32", "--batch-size", "100"]
